# This is the .toml file passed to Locomotion.
# For information on the different settings available, and an example file,
# see the Locomotion README: https://github.com/leoncvlt/loconotion/blob/master/README.md

# DO NOT CHANGE THIS VALUE. The deploy script relies on the site being deployed to the
# "site" directory.
name = "site"

# This page should be the root of your website. It's important.
page = "https://romantic-peripheral-720.notion.site/Adam-Schnitzer-878fc94cec3a4bf7bc9eb914f565fb98"

[site]
  [[site.inject.head.script]]
  type="text/javascript"
  src="/ga.js"
  
  [[site.inject.head.script]]
  inner_html="""
  <!-- Global site tag (gtag.js) - Google Analytics -->
  <script async src="https://www.googletagmanager.com/gtag/js?id=UA-5990359-3"></script>
  <script>
    window.dataLayer = window.dataLayer || [];
    function gtag(){dataLayer.push(arguments);}
    gtag('js', new Date());

    gtag('config', 'UA-5990359-3');
  </script>
  """
